### ISSUE TITLE
So badly openaq  tutorail for use openaq python package,is rubbish and awful !

### ISSUE THREAD

**Issue by mullerhai** [openaq/openaq-python#39]
### Description

oh my god ,first use so badly tutorial for  this ,and even I don't find how to get the air quality data  example like pandas dataframe.
why ？ is your team have no time to write ,and the v3 api is can not safe suit the v2 v1. baddly experience 

### Python, openaq & OS Version

```Text
s
```

**Comment by russbiggs** [comment]
Contributions to improve the package as well-formed bug reports or feature requests are welcome. Note the package is still in a pre 1.0.0 release and under active development. 

We encourage you to be constructive in your feedback and follow our Code of Conduct, which you can find here: [Code of Conduct](https://github.com/openaq/openaq-python?tab=coc-ov-file)

The Code of Conduct outlines our commitment to a welcoming and respectful environment for everyone in the OpenAQ community. It ensures we can all learn and collaborate effectively.

**Comment by mullerhai** [comment]
> Contributions to improve the package as well-formed bug reports or feature requests are welcome. Note the package is still in a pre 1.0.0 release and under active development.
> 
> We encourage you to be constructive in your feedback and follow our Code of Conduct, which you can find here: [Code of Conduct](https://github.com/openaq/openaq-python?tab=coc-ov-file)
> 
> The Code of Conduct outlines our commitment to a welcoming and respectful environment for everyone in the OpenAQ community. It ensures we can all learn and collaborate effectively.

I am feel sorry to report this.but  I eagerly  need the aqi data, so  use waqi
